[package]
name = "sort_by_derive"
version = "0.1.0"
edition = "2021"
license = "Unlicense"
description = "Derive macro `#[derive(SortBy)]`, deriving traits `Ord`, `PartialOrd`, `Eq`, `PartialEq` and `Hash` for structs that can't automatically derive from those traits."
homepage = "https://github.com/valsteen/sort_by_derive"
documentation = "https://github.com/valsteen/sort_by_derive/#readme"
repository = "https://github.com/valsteen/sort_by_derive"
keywords = ["macro", "derive", "ordering", "sorting"]
categories = ["development-tools"]

[lib]
proc-macro = true

[dependencies]
itertools = "0.10.3"
proc-macro2 = "1.0.43"
syn = "1.0.99"
quote = "1.0.21"
rust-format = "0.3.4"

